version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - DOCKERIZED=false
      - DB_HOST_EXTERNAL=${DB_HOST_EXTERNAL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_EXTERNAL_PORT=${DATABASE_EXTERNAL_PORT}
      - DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}
      - DB_QUEUE_LIMIT=${DB_QUEUE_LIMIT}
      - DB_WAIT_FOR_CONNECTIONS=${DB_WAIT_FOR_CONNECTIONS}
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_INTERNAL_PORT}"
    environment:
      - REACT_APP_API_URL=${BACKEND_URL}
    depends_on:
      - backend
    restart: always

  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: gps
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: Utalca_123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

# volumes:
#   db_data:
